
#server.port=5000
spring.application.name=logistic

#spring.datasource.url=jdbc:mysql://localhost:3306/logistics_logic
#spring.datasource.username=root
#spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://31.97.232.175:3306/logistics_logic
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=dbadmin
spring.datasource.password=OneUniq@1234

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=18000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=30000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html


# ---- REDIS ----
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# Enable caching globally
spring.main.allow-bean-definition-overriding=true

#log4j.rootLogger=DEBUG,console,R
#log4j.rootLogger=INFO, FILE

# ---- EMAIL (Gmail SMTP) ----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=1uniq.transport@gmail.com
spring.mail.password=tuyr fssq rjgk rxqj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.company.name=1UNIQ Transport
app.company.support.email=1uniq.transport@gmail.com

logging.config=classpath:log4j2.properties
#logging.file.path=classpath:logback-spring.xml

#log4j.rootLogger=DEBUG,CONSOLE,FILE
#log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
#log4j.appender.FILE=org.apache.log4j.RollingFileAppender
#log4j.appender.FILE.File=output/log.log
#log4j.appender.CONSOLE.Threshold=INFO
#log4j.appender.FILE.Threshold=DEBUGlogging.file.name=app_run.log

