
server.port=${PORT:8080}
spring.application.name=logistic

spring.datasource.url=${DATABASE_URL:jdbc:mysql://31.97.232.175:3306/logistics_logic}
spring.datasource.username=${DATABASE_USERNAME:dbadmin}
spring.datasource.password=${DATABASE_PASSWORD:OneUniq@1234}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=18000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=30000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

# Disable Redis cache (not available on Render)
spring.cache.type=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

spring.main.allow-bean-definition-overriding=true

logging.config=classpath:log4j2.properties

logging.config=classpath:log4j2.properties
#logging.file.path=classpath:logback-spring.xml

#log4j.rootLogger=DEBUG,CONSOLE,FILE
#log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
#log4j.appender.FILE=org.apache.log4j.RollingFileAppender
#log4j.appender.FILE.File=output/log.log
#log4j.appender.CONSOLE.Threshold=INFO
#log4j.appender.FILE.Threshold=DEBUG